# Generated by Django 3.0.5 on 2020-04-13 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
