# Generated by Django 3.0.5 on 2020-04-13 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_delete_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asset_submission',
        ),
    ]
