# Generated by Django 3.0.5 on 2020-04-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_asset_submission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asset_submission',
            new_name='asset_management',
        ),
    ]
