# Generated by Django 3.0.5 on 2020-04-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20200414_1343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asset_management',
            new_name='asset_submission',
        ),
    ]
