# Generated by Django 3.0.5 on 2020-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20200414_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_submission',
            name='approval_status',
            field=models.BooleanField(default='False'),
        ),
    ]
