# Generated by Django 3.0.5 on 2020-04-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_asset_submission_approval_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asset_submission',
            new_name='Asset_Submission_Model',
        ),
    ]
