# Generated by Django 3.0.5 on 2020-04-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_asset_submission_model_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_submission_model',
            name='headset',
            field=models.BooleanField(default='False', verbose_name='headset'),
        ),
        migrations.AddField(
            model_name='asset_submission_model',
            name='keyboard',
            field=models.BooleanField(default='False', verbose_name='keyboard'),
        ),
        migrations.AddField(
            model_name='asset_submission_model',
            name='mouse',
            field=models.BooleanField(default='False', verbose_name='mouse'),
        ),
    ]
