# Generated by Django 3.0.5 on 2020-04-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_auto_20200418_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_submission_model',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
